const Q=[
['美玲在情緒激動時，會變成甚麼動物？',['紅熊貓','北極熊','小白兔'],0],
['美玲平日最重視哪一群人的陪伴？',['她的好朋友','陌生遊客','電視主持'],0],
['美玲和朋友們最喜歡哪一個偶像團體？',['四城男孩','天空樂隊','熊貓合唱團'],0],
['美玲第一次變成紅熊貓時，最主要的感受是甚麼？',['驚訝和慌張','十分平靜','完全不在意'],0],
['美玲的媽媽對女兒抱有甚麼態度？',['關心但要求較高','完全不理會','只顧自己玩樂'],0],
['美玲需要學習如何處理甚麼？',['自己的情緒和成長變化','駕駛飛機','照顧農場'],0],
['朋友們對美玲的紅熊貓秘密有甚麼反應？',['接納並支持她','立即離開她','假裝不認識她'],0],
['故事中，紅熊貓象徵甚麼？',['情緒、成長和真實的自己','只是一件玩具','一場普通比賽'],0],
['美玲最後明白，面對家人的期望時應該怎樣做？',['勇敢表達自己的想法','永遠隱藏感受','逃避所有問題'],0],
['《熊抱青春記》最重要的信息之一是甚麼？',['接納自己並珍惜家人朋友','只要得到第一名','永遠不要改變'],0]
];
const c=document.getElementById('game'),x=c.getContext('2d'),$=id=>document.getElementById(id);
let W,H,D=1,last=0,run=false,q=0,lives=5,score=0,start=0,keys={},jump=false,lock=false,cam=0,plats=[],gifts=[],power=null,powerEnd=0;
const p={x:60,y:0,w:40,h:60,vx:0,vy:0,on:true,face:1,scale:1,wings:false,cat:false};
let checkpoint={x:60,y:0};
const GAP=180,GRAV=1800,JUMP=740,SPEED=330;
function ground(){return 0}function ly(i){return 120+i*GAP}function sy(y){return H-80-(y-cam)}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0);makeWorld()}addEventListener('resize',resize);
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!keys.Space)jump=true;keys[e.code]=true});
addEventListener('keyup',e=>keys[e.code]=false);
function makeWorld(){const pw=Math.max(145,Math.min(205,W*.18)),gap=Math.max(16,(W-pw*3)/4);plats=[];for(let i=0;i<10;i++){const order=[0,1,2].sort(()=>Math.random()-.5);for(let j=0;j<3;j++)plats.push({q:i,a:order[j],x:gap+j*(pw+gap),y:ly(i),w:pw,h:24,used:false,show:true})}gifts=[{x:W*.87,y:ly(1)+80,s:50,t:false},{x:W*.13,y:ly(4)+80,s:50,t:false},{x:W*.87,y:ly(7)+80,s:50,t:false}]}
function setQ(){if(q>=10)return finish();$('qNum').textContent=q+1;$('question').innerHTML=Q[q][0]+'<div class="sub">跳到更高一層的正確答案平台</div>'}
function hearts(){$('hearts').textContent='♥ '.repeat(lives)+'♡ '.repeat(5-lives)}function toast(t,ok=true){$('toast').textContent=t;$('toast').style.color=ok?'#9fffd4':'#ff9bad';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1300)}
function reset(){p.x=checkpoint.x;p.y=checkpoint.y;p.vx=0;p.vy=0;p.on=true;lock=false;keys.Space=false;jump=false}
function choose(o){if(lock)return;lock=true;o.used=true;if(o.a===Q[q][2]){score+=100;checkpoint={x:o.x+o.w/2-p.w/2,y:o.y};toast('答對了！繼續向上！');setTimeout(()=>{q++;lock=false;setQ()},550)}else{o.show=false;lives--;hearts();toast('答錯了！平台消失。',false);setTimeout(()=>{if(lives<=0)finish(false);else reset()},600)}}
function lose(){if(lock)return;lock=true;lives--;hearts();toast('掉下去了！失去一條生命。',false);setTimeout(()=>{if(lives<=0)finish(false);else reset()},600)}
function update(dt){if(!run)return;const sp=power===1?420:SPEED,jp=p.wings?900:JUMP;p.vx=0;if(keys.ArrowLeft){p.vx=-sp;p.face=-1}if(keys.ArrowRight){p.vx=sp;p.face=1}if(jump){if(p.on&&!lock){p.vy=jp;p.on=false}jump=false}p.vy-=GRAV*dt;const old=p.y;p.x=Math.max(0,Math.min(W-p.w,p.x+p.vx*dt));p.y+=p.vy*dt;p.on=false;if(p.vy<=0&&!lock){for(const o of plats){if(o.q!==q||o.used||!o.show)continue;const h=p.x+p.w>o.x+3&&p.x<o.x+o.w-3;const cross=old>=o.y-8&&p.y<=o.y+8;if(h&&cross){p.y=o.y;p.vy=0;p.on=true;choose(o);break}}}if(q===0&&p.y<=0){p.y=0;p.vy=0;p.on=true}if(p.y<checkpoint.y-170)lose();const target=Math.max(0,p.y-H*.42);cam+=(target-cam)*.08;if(power!==null){const left=Math.max(0,Math.ceil((powerEnd-performance.now())/1000));$('timer').textContent=left+' 秒';if(!left){power=null;p.wings=false;p.scale=1;p.cat=false;$('power').style.display='none'}}}
c.addEventListener('click',e=>{if(!run)return;const r=c.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;for(const g of gifts){const yy=sy(g.y);if(!g.t&&mx>g.x-g.s/2&&mx<g.x+g.s/2&&my>yy-g.s/2&&my<yy+g.s/2){g.t=true;const n=Math.floor(Math.random()*3),names=['翅膀模式','巨人模式','小貓模式'];power=n;powerEnd=performance.now()+60000;p.wings=n===0;p.scale=n===1?1.35:1;p.cat=n===2;$('power').style.display='block';$('powerName').textContent='神秘能力：'+names[n];toast('取得「'+names[n]+'」60秒！');break}}});
function rr(a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r)}
function draw(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#100a44');g.addColorStop(.6,'#372c7e');g.addColorStop(1,'#6c54bd');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#fff';for(let i=0;i<95;i++)x.fillRect((i*137)%W,((i*83-cam*.15)%H+H)%H,i%8?1:2,i%8?1:2);drawCastle();const gy=sy(0);x.fillStyle='#6b4ad1';x.fillRect(0,gy,W,H-gy);x.fillStyle='#9b82ee';for(let a=0;a<W;a+=48)x.fillRect(a,gy,44,12);for(let i=0;i<plats.length;i++){const o=plats[i];if(!o.show)continue;const yy=sy(o.y);if(yy<-100||yy>H+100)continue;const col=['#f5c84d','#59d9ef','#ef80c6'][i%3];x.fillStyle=col;rr(o.x,yy,o.w,o.h,8);x.fill();x.fillStyle='#241957';rr(o.x,yy-52,o.w,40,11);x.fill();x.strokeStyle='#ffffff77';x.stroke();x.fillStyle='#fff';x.font='bold 17px Microsoft JhengHei';x.textAlign='center';x.textBaseline='middle';x.fillText(Q[o.q][1][o.a],o.x+o.w/2,yy-32,o.w-12)}for(const a of gifts){if(a.t)continue;const yy=sy(a.y);if(yy<-60||yy>H+60)continue;x.save();x.translate(a.x,yy);x.shadowBlur=28;x.shadowColor='#ffe66d';x.fillStyle='#ffd75f';rr(-a.s/2,-a.s/2,a.s,a.s,9);x.fill();x.fillStyle='#ff86c7';x.fillRect(-5,-a.s/2,10,a.s);x.fillRect(-a.s/2,-5,a.s,10);x.fillStyle='#fff';x.font='bold 18px sans-serif';x.textAlign='center';x.fillText('?',0,6);x.restore()}drawPlayer()}
function drawCastle(){const yy=sy(ly(9)+220);if(yy<-250||yy>H+200)return;x.fillStyle='#e9c9ff';x.fillRect(W/2-130,yy-90,260,130);x.fillStyle='#765dff';x.beginPath();x.moveTo(W/2-150,yy-90);x.lineTo(W/2-80,yy-180);x.lineTo(W/2-10,yy-90);x.fill();x.beginPath();x.moveTo(W/2+10,yy-90);x.lineTo(W/2+80,yy-180);x.lineTo(W/2+150,yy-90);x.fill();x.fillStyle='#362564';x.font='bold 22px Microsoft JhengHei';x.textAlign='center';x.fillText('故事書城堡',W/2,yy-25)}
function drawPlayer(){const yy=sy(p.y);x.save();x.translate(p.x+p.w/2,yy);x.scale(p.face*p.scale,p.scale);if(p.wings){x.fillStyle='#eefaffdd';x.beginPath();x.ellipse(-25,-33,17,25,-.5,0,Math.PI*2);x.ellipse(25,-33,17,25,.5,0,Math.PI*2);x.fill()}x.fillStyle=p.cat?'#f49a45':'#5478ef';rr(-18,-50,36,50,14);x.fill();x.fillStyle='#ffd0a8';x.beginPath();x.arc(0,-61,16,0,Math.PI*2);x.fill();x.fillStyle='#37221d';x.beginPath();x.arc(0,-66,17,Math.PI,0);x.fill();x.restore()}
function loop(t){const dt=Math.min((t-last)/1000||0,.033);last=t;update(dt);draw();requestAnimationFrame(loop)}
function finish(win=true){if(!run)return;run=false;$('hud').classList.add('hide');$('end').classList.remove('hide');$('endTitle').textContent=win?'成功抵達故事書城堡！':'冒險暫告一段落';$('resultText').innerHTML='姓名：'+$('name').value+'<br>答對：'+q+'/10 題<br>分數：'+score+' 分<br>剩餘生命：'+lives+'<br>時間：'+Math.round((Date.now()-start)/1000)+' 秒'}
$('play').onclick=()=>{if(!$('name').value.trim())return alert('請先輸入姓名');$('playerName').textContent=$('name').value.trim();$('start').classList.add('hide');$('hud').classList.remove('hide');run=true;start=Date.now();checkpoint={x:60,y:0};reset();setQ()};resize();requestAnimationFrame(loop);